version: '3'
services:
  db:
    image: postgres:15
    container_name: hive5_postgres
    restart: always
    environment:
      POSTGRES_DB: hive5_db
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: